<?php error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
$this->pdf->setPrintHeader($header,$type,$duration);
$this->pdf->setPrintFooter(true);

$this->pdf->SetFont('helvetica', 'B', 16);
$this->pdf->AddPage($orientation,$page); 



foreach($branch as $ress){
    $branch_name=$ress->name;
    $this->pdf->headerSet3($ress->name,$ress->address,$ress->tp,$ress->fax,$ress->email);
}
$this->pdf->Ln();


foreach($data as $row){
    $credit_limit =$row->credit_limit;
    $code=$row->code;
    $full_name=$row->name;
    $nic =$row->nic;
    $addr1=$row->address1;
    $addr2=$row->address2;
    $addr3=$row->address3;
    $email=$row->email;
    $tp=$row->cus_tp;
    $occupation=$row->occupation;
    $company_name=$row->company_name;
    $c_p_name=$row->cn_name;
    $c_p_addr=$row->cn_address;
    $c_p_tel=$row->cn_tel;
    $c_p_email=$row->cn_email;
    $t_reg=$row->tax_reg_no;
    $credit_period=$row->credit_period;
    $other_contact=explode(',',$row->cus_tp);

}

$this->pdf->SetLineStyle(array('width' => 0.1, 'cap' => 'butt', 'join' => 'miter', 'dash' => 0.1, 'color' => array(0, 0, 0)));
$this->pdf->SetFont('helvetica','B',11);
$this->pdf->Cell(60, 6," ", '0', 0, 'C', 0);
$this->pdf->Cell(35, 6," Customer Details", 'u', 0, 'C', 0);
$this->pdf->Ln();
$this->pdf->Ln();
$this->pdf->SetFont('helvetica','B',8);
$this->pdf->Cell(22, 6," Loan Amount", '0', 0, 'L', 0);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(25, 6, $credit_limit, '0', 0, 'L', 0);
$this->pdf->Cell(27, 6,"", '0', 0, 'L', 0);
$this->pdf->SetFont('helvetica','B',8);
$this->pdf->Cell(15, 6," Loan No", '0', 0, 'L', 0);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(25, 6,$code, '0', 0, 'L', 0);
$this->pdf->Cell(26, 6,"", '0', 0, 'L', 0);
$this->pdf->SetFont('helvetica','B',8);
$this->pdf->Cell(15, 6," Branch", '0', 0, 'L', 0);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(25, 6,$branch_name, '0', 0, 'L', 0);
$this->pdf->Ln();
$this->pdf->Ln();
$heigh=6*(max(1,$this->pdf->getNumLines($full_name,140)));
$this->pdf->SetFont('helvetica','B',8);
$this->pdf->MultiCell(40, $heigh,"Customer Full Name",1, 'L',false, 0, '', '', true, 0, false, true, $heigh,'M' ,false);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->MultiCell(140, $heigh,$full_name,1, 'L',false, 0, '', '', true, 0, false, true, $heigh,'M' ,false);
$this->pdf->Ln();
$this->pdf->SetFont('helvetica','B',8);
$this->pdf->Cell(40, 6," NIC NO ", '1', 0, 'L', 0);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(140, 6,"", '1', 0, 'L', 0);
$this->pdf->Ln();
$heigh_a=6*(max(1,$this->pdf->getNumLines($addr1." ".$addr2." ".$addr3,140)));
$this->pdf->SetFont('helvetica','B',8);
$this->pdf->MultiCell(40, $heigh_a,"Address",1, 'L',false, 0, '', '', true, 0, false, true, $heigh_a,'M' ,false);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->MultiCell(140, $heigh_a,$addr1." ".$addr2." ".$addr3,1, 'L',false, 0, '', '', true, 0, false, true, $heigh_a,'M' ,false);
$this->pdf->Ln();
$this->pdf->SetFont('helvetica','B',8);
$this->pdf->Cell(40, 6,"Email ", '1', 0, 'L', 0);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(140, 6,$email, '1', 0, 'L', 0);
$this->pdf->Ln();
$this->pdf->SetFont('helvetica','B',8);
$this->pdf->Cell(40, 6,"Telephone No ", '1', 0, 'L', 0);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(140, 6,$other_contact[0].",".$other_contact[1], '1', 0, 'L', 0);
$this->pdf->Ln();
$this->pdf->SetFont('helvetica','B',8);
$this->pdf->Cell(40, 6,"Occupation", '1', 0, 'L', 0);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(140, 6,$occupation, '1', 0, 'L', 0);
$this->pdf->Ln();
$this->pdf->SetFont('helvetica','B',8);
$this->pdf->Cell(40, 6,"Company Name", '1', 0, 'L', 0);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(140, 6,$company_name, '1', 0, 'L', 0);
$this->pdf->Ln();
$this->pdf->SetFont('helvetica','B',8);
$this->pdf->Cell(40, 6,"Contact Person Details", 'LR', 0, 'L', 0);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(140, 6,"Name :" .$c_p_name, 'LR', 0, 'L', 0);
$this->pdf->Ln(); 
$this->pdf->SetFont('helvetica','B',8);
$this->pdf->Cell(40, 6,"", 'LR', 0, 'L', 0);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(140, 6,"Address :" .$c_p_addr, 'LR', 0, 'L', 0);
$this->pdf->Ln();  
$this->pdf->SetFont('helvetica','B',8); 
$this->pdf->Cell(40, 6,"", 'LR', 0, 'L', 0);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(140, 6,"Tel No :" .$c_p_tel, 'LR', 0, 'L', 0);
$this->pdf->Ln(); 
$this->pdf->SetFont('helvetica','B',8);  
$this->pdf->Cell(40, 6,"", 'LR', 0, 'L', 0);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(140, 6,"Email :" .$c_p_email, 'LR', 0, 'L', 0);
$this->pdf->Ln(); 
$this->pdf->SetFont('helvetica','B',8);  
$this->pdf->Cell(40, 6,"", 'LR', 0, 'L', 0);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(140, 6,$other_contact[2], 'LR', 0, 'L', 0);
$this->pdf->Ln(); 
$this->pdf->SetFont('helvetica','B',8);  
$this->pdf->Cell(40, 6,"", 'LR', 0, 'L', 0);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(140, 6,$other_contact[3], 'LR', 0, 'L', 0);
$this->pdf->Ln();
$this->pdf->SetFont('helvetica','B',8);     
$this->pdf->Cell(40, 6,"Tax Registered To", '1', 0, 'L', 0);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(140, 6,$t_reg, '1', 0, 'L', 0);
$this->pdf->Ln(); 
$this->pdf->SetFont('helvetica','B',8);
$this->pdf->Cell(40, 6,"Credit Period", '1', 0, 'L', 0);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(140, 6,$credit_period, '1', 0, 'L', 0);
$this->pdf->Ln();
$this->pdf->SetFont('helvetica','B',8);  
$this->pdf->Cell(40, 6,"Customer Place Map", '1', 0, 'L', 0);
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(140, 6,"", '1', 0, 'L', 0);
$this->pdf->Ln();
$this->pdf->Ln();
$this->pdf->SetFont('helvetica','B',8);
$this->pdf->Cell(100, 6,"I confirm that the information given above is true and correct ", '0', 0, 'L', 0);
$this->pdf->Ln();
$this->pdf->Ln();
$this->pdf->SetFont('helvetica','',8);
$this->pdf->Cell(40, 6,"...................................", '0', 0, 'C', 0);
$this->pdf->Cell(50, 6,"", '0', 0, 'L', 0);
$this->pdf->Cell(50, 6,"", '0', 0, 'L', 0);
$this->pdf->Cell(40, 6,"...................................", '0', 0, 'C', 0);
$this->pdf->Ln();
$this->pdf->SetFont('helvetica','B',8);
$this->pdf->Cell(40, 6,"Date", '0', 0, 'C', 0);
$this->pdf->Cell(50, 6,"", '0', 0, 'L', 0);
$this->pdf->Cell(50, 6,"", '0', 0, 'L', 0);
$this->pdf->Cell(40, 6,"Customer Signature", '0', 0, 'C', 0);
$this->pdf->Output("Customer Form".date('Y-m-d').".pdf", 'I');
?>
